// This file has been autogenerated from a class added in the UI designer.

using System;
using Plugin.Geolocator.Abstractions;
using UIKit;

namespace UberBlablaCar2Go
{
	public partial class DestinationController : UIViewController
	{
		public DestinationController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.OkButton.TouchUpInside += this.OkButtonClicked;
			this.GetLocationAndSetMap ();
			//this.DestinationField.Text = "Bahnhof Stuttgart Bad Cannstatt";
		}

		Position position;

		public string Mode { get; internal set; }

		private async void GetLocationAndSetMap ()
		{
			this.position = await LocationService.GetLocation ();
		}

		void OkButtonClicked (object sender, EventArgs e)
		{
			if (Mode == "Driver") {
				this.PerformSegue ("DriverSegue", this);
			} else {
				this.PerformSegue ("RiderSegue", this);
			}
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, Foundation.NSObject sender)
		{
			IDestination target = (IDestination)segue.DestinationViewController;
			target.SetDestination (this.position, this.DestinationField.Text);
			base.PrepareForSegue (segue, sender);
		}
	}
}
